name: Copy Orbit-Simulator Repository 

on:
  push:
    branches:
      - master # Change if you want to copy another branch of your repository
  workflow_dispatch:

jobs:
  copy_repository:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Orbit-Simulator Repository
        uses: actions/checkout@v2

      - name: Push directory to another repository directory
        # GitHub access token
        env:
          API_TOKEN_GITHUB: '${{ secrets.API_TOKEN_GITHUB }}'
        # You may pin to the exact commit or the version.
        # uses: XenonMolecule/github-action-push-to-another-repository@de389add933e78b040fd9274822bd171ac87b26e
        uses: mishavoloshchuk/github-action-push-to-another-repository
        with:
          # Comment line to use default value if there is default value
          # Source directory from the origin directory
          source-directory: '.'
          # Name of the destination username/organization
          destination-github-username: 'mishavoloshchuk'
          # Destination repository
          destination-repository-name: 'mishavoloshchuk.github.io'
          # Email for the git commit
          user-email: 'actions@github.com'
          # [Optional] Name for the git commit. Defaults to the destination username/organization name
          user-name: 'actions_bot' # optional, default is 
          # [Optional] Username/organization for the destination repository
          destination-repository-username: 'mishavoloshchuk' # optional, default is 
          # [Optional] set target branch name for the destination repository. Defaults to "master" for historical reasons
          target-branch: 'main' # Set the destination branch (default is master)
          # [Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo
  #          commit-message: # optional, default is Update from ORIGIN_COMMIT
          # [Optional] The directory to wipe and replace in the target repository
          target-directory: 'projects/Orbit-Simulator' # optional, default is .
